### ISSUE TITLE
Is filter size depends on scale factor?

### ISSUE THREAD

**Issue by mrgloom** [trevor-m/tensorflow-bicubic-downsample#2]
I wonder how filter size is depending on scale factor?
Seems filter size = factor*4 can you elaborate on this?
https://github.com/trevor-m/tensorflow-bicubic-downsample/blob/master/bicubic_downsample.py#L13

**Comment by trevor-m** [comment]
If you print the kernel after https://github.com/trevor-m/tensorflow-bicubic-downsample/blob/master/bicubic_downsample.py#L18 you can see that anything beyond a filter size of 8 for factor =2 will just have zeros, so there is no point in having a larger filter.

Filter size = 8: `[-0.01171875 -0.03515625  0.11328125  0.43359375  0.43359375  0.11328125
 -0.03515625 -0.01171875]`
Filter size = 16: `[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
 -0.01171875 -0.03515625  0.11328125  0.43359375  0.43359375  0.11328125
 -0.03515625 -0.01171875  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.        ]`

The same phenomenon happens with factor=4 when comparing filter size 16 (4\*4) with larger filters.
I'm sure there is a better mathematical explanation for this, but I found the factor*4 relationship to work for these common cases.
